import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient

from dotenv import load_dotenv
load_dotenv()  # loading environment variables

MONGODB_CONNECTION_STRING = os.getenv("MONGODB_CONNECTION_STRING")
# Asynchronous MongoDB connection
async_connection_string = f'{MONGODB_CONNECTION_STRING}'  # This can be the same as the synchronous connection string
async_mdb_client = AsyncIOMotorClient(async_connection_string)  # setting mongodb client for asynchronous operations
async_database = async_mdb_client['fastapi_db']  # database name in mongodb for asynchronous operations

# Function to validate connection
async def validate_mongodb_connection():
    try:
        # Attempt to count documents in a specific collection, e.g., 'test_collection'
        count = await async_database['test_collection'].count_documents({})
        print(f"Connection Successful! Found {count} documents in 'test_collection'.")
    except Exception as e:
        print("Connection to MongoDB failed")

####################### Update quiz_data here ##################
quiz_data = {'id': '1',
 'questions': [{'id': '1',
   'question': '1. You regularly make new friends.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '2',
   'question': '2. You spend a lot of your free time exploring various random topics that pique your interest.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '3',
   'question': '3. Seeing other people cry can easily make you feel like you want to cry too.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '4',
   'question': '4. You often make a backup plan for a backup plan.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '5',
   'question': '5. You usually stay calm, even under a lot of pressure.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '6',
   'question': '6. At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '7',
   'question': '7. You prefer to completely finish one project before starting another.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '8',
   'question': '8. You are very sentimental.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '9',
   'question': '9. You like to use organizing tools like schedules and lists.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '10',
   'question': '10. Even a small mistake can cause you to doubt your overall abilities and knowledge.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '11',
   'question': '11. You feel comfortable just walking up to someone you find interesting and striking up a conversation.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '12',
   'question': '12. You are not too interested in discussing various interpretations and analyses of creative works.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '13',
   'question': '13. You are more inclined to follow your head than your heart.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '14',
   'question': '14. You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '15',
   'question': '15. You rarely worry about whether you make a good impression on people you meet.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '16',
   'question': '16. You enjoy participating in group activities.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '17',
   'question': '17. You like books and movies that make you come up with your own interpretation of the ending.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '18',
   'question': '18. Your happiness comes more from helping others accomplish things than your own accomplishments.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '19',
   'question': '19. You are interested in so many things that you find it difficult to choose what to try next.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '20',
   'question': '20. You are prone to worrying that things will take a turn for the worse.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '21',
   'question': '21. You avoid leadership roles in group settings.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '22',
   'question': '22. You are definitely not an artistic type of person.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '23',
   'question': '23. You think the world would be a better place if people relied more on rationality and less on their feelings.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '24',
   'question': '24. You prefer to do your chores before allowing yourself to relax.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '25',
   'question': '25. You enjoy watching people argue.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '26',
   'question': '26. You tend to avoid drawing attention to yourself.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '27',
   'question': '27. Your mood can change very quickly.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '28',
   'question': '28. You lose patience with people who are not as efficient as you.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '29',
   'question': '29. You often end up doing things at the last possible moment.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '30',
   'question': '30. You have always been fascinated by the question of what, if anything, happens after death.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '31',
   'question': '31. You usually prefer to be around others rather than on your own.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '32',
   'question': '32. You become bored or lose interest when the discussion gets highly theoretical.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '33',
   'question': '33. You find it easy to empathize with a person whose experiences are very different from yours.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '34',
   'question': '34. You usually postpone finalizing decisions for as long as possible.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '35',
   'question': '35. You rarely second-guess the choices that you have made.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '36',
   'question': '36. After a long and exhausting week, a lively social event is just what you need.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '37',
   'question': '37. You enjoy going to art museums.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '38',
   'question': '38. You often have a hard time understanding other people’s feelings.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '39',
   'question': '39. You like to have a to-do list for each day.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '40',
   'question': '40 You rarely feel insecure.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '41',
   'question': '41. You avoid making phone calls.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '42',
   'question': '42. You often spend a lot of time trying to understand views that are very different from your own.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '43',
   'question': '43. In your social circle, you are often the one who contacts your friends and initiates activities.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '44',
   'question': '44. If your plans are interrupted, your top priority is to get back on track as soon as possible.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '45',
   'question': '45. You are still bothered by mistakes that you made a long time ago.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '46',
   'question': '46. You rarely contemplate the reasons for human existence or the meaning of life.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '47',
   'question': '47. Your emotions control you more than you control them.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '48',
   'question': '48. You take great care not to make people look bad, even when it is completely their fault.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '49',
   'question': '49. Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '50',
   'question': '50. When someone thinks highly of you, you wonder how long it will take them to feel disappointed in you.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '51',
   'question': '51. You would love a job that requires you to work alone most of the time.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '52',
   'question': '52. You believe that pondering abstract philosophical questions is a waste of time.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '53',
   'question': '53. You feel more drawn to places with busy, bustling atmospheres than quiet, intimate places.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '54',
   'question': '54. You know at first glance how someone is feeling.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '55',
   'question': '55. You often feel overwhelmed.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '56',
   'question': '56. You complete things methodically without skipping over any steps.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '57',
   'question': '57. You are very intrigued by things labeled as controversial.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '58',
   'question': '58. You would pass along a good opportunity if you thought someone else needed it more.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '59',
   'question': '59. You struggle with deadlines.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']},
  {'id': '60',
   'question': '60. You feel confident that things will work out for you.',
   'options': ['Fully Agree',
    'Partially Agree',
    'Slightly Agree',
    'Neutral',
    'Slightly Disagree',
    'Partially Disagree',
    'Fully Disagree']}]}

###############################################################
# Running the validation function
if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(validate_mongodb_connection())
    async_database.quizes.insert_one(quiz_data)
